2021/06/16 09:38:04 : Error Connecting:HTTPConnectionPool(host='127.0.1.1', port=8080): Max retries exceeded with url: /api/v1/action/setup_cart (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbfa00b2c70>: Failed to establish a new connection: [Errno 111] Connection refused')) : False
2021/06/16 09:39:08 : Error Connecting:HTTPConnectionPool(host='127.0.1.1', port=8080): Max retries exceeded with url: /api/v1/action/setup_cart (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbe8f836c70>: Failed to establish a new connection: [Errno 111] Connection refused')) : False
2021/06/16 09:39:30 : Error Connecting:HTTPConnectionPool(host='127.0.1.1', port=8080): Max retries exceeded with url: /api/v1/action/setup_cart (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f94b6d8eeb0>: Failed to establish a new connection: [Errno 111] Connection refused')) : False
2021/06/16 09:41:17 : Error Connecting:HTTPConnectionPool(host='127.0.1.1', port=8080): Max retries exceeded with url: /api/v1/action/setup_cart (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff43515ceb0>: Failed to establish a new connection: [Errno 111] Connection refused')) : False
2021/06/16 09:41:42 : Error Connecting:HTTPConnectionPool(host='127.0.1.1', port=8080): Max retries exceeded with url: /api/v1/action/setup_cart (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe36e56eeb0>: Failed to establish a new connection: [Errno 111] Connection refused')) : False
2021/06/16 09:42:44 : Error Connecting:HTTPConnectionPool(host='127.0.1.1', port=8080): Max retries exceeded with url: /api/v1/action/setup_cart (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdbd7d2eeb0>: Failed to establish a new connection: [Errno 111] Connection refused')) : False
2021/06/16 09:42:58 : Error Connecting:HTTPConnectionPool(host='127.0.1.1', port=8080): Max retries exceeded with url: /api/v1/action/setup_cart (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffb41a38eb0>: Failed to establish a new connection: [Errno 111] Connection refused')) : False
2021/06/16 09:46:41 : Error Connecting:HTTPConnectionPool(host='127.0.1.1', port=8080): Max retries exceeded with url: /api/v1/action/setup_cart (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f63d319beb0>: Failed to establish a new connection: [Errno 111] Connection refused')) : False
2021/06/16 09:47:22 : Error Connecting:HTTPConnectionPool(host='127.0.1.1', port=8080): Max retries exceeded with url: /api/v1/action/setup_cart (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5fea19ceb0>: Failed to establish a new connection: [Errno 111] Connection refused')) : False
2021/06/21 10:21:09 : Error Connecting:HTTPConnectionPool(host='127.0.1.1', port=8080): Max retries exceeded with url: /api/v1/action/setup_cart (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4030280e20>: Failed to establish a new connection: [Errno 111] Connection refused')) : False
2021/06/21 10:22:48 : Error Connecting:HTTPConnectionPool(host='127.0.1.1', port=8080): Max retries exceeded with url: /api/v1/action/setup_cart (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2b69d3ae20>: Failed to establish a new connection: [Errno 111] Connection refused')) : False
2021/06/21 10:33:30 : Error Connecting:HTTPConnectionPool(host='127.0.1.1', port=8080): Max retries exceeded with url: /api/v1/action/setup_cart (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6cd620fe20>: Failed to establish a new connection: [Errno 111] Connection refused')) : False
